# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_auto_20170821_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='expiry',
            field=models.DateTimeField(),
        ),
    ]
