version: '3'

services:
  db2:
      image: postgres
      ports:
        - "8002:5432"
  #db:
  #  image: postgres
  #  ports:
  #    - "8002:5432"
  web:
    build: .
    command: python3 caracolapi/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db2