# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.4 on 2017-08-23 00:30
=======
# Generated by Django 1.11.4 on 2017-08-22 06:05
>>>>>>> master
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0003_auto_20170821_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.CharField(max_length=100)),
                ('order', models.TextField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStored',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order_token', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.AppUser')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
