# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0004_orderrequested_orderstored'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_description', models.CharField(max_length=100)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
    ]
