# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0007_orderstored_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='user_rights',
            field=models.CharField(default='client', max_length=100),
        ),
    ]
